import { faker } from "@faker-js/faker";

export const animalFn = [
  {
    funcName: "Pet Name",
    funcDesc: "Generates a random pet name.",
    func: faker.animal.petName,
    callSignature: "faker:animal:petName",
    tags: ["animal"],
  },

  {
    funcName: "Animal Type",
    funcDesc: "Gives a random animal type.",
    func: faker.animal.type,
    callSignature: "faker:animal:type",
    tags: ["animal"],
  },
  {
    funcName: "Bird Name",
    funcDesc: "Generates a random bird name.",
    func: faker.animal.bird,
    callSignature: "faker:animal:bird",
    tags: ["animal"],
  },
  {
    funcName: "Cat Name",
    funcDesc: "Generates a random cat name.",
    func: faker.animal.cat,
    callSignature: "faker:animal:cat",
    tags: ["animal"],
  },
  {
    funcName: "Cetacean Name",
    funcDesc: "Generates a random cetacean name.",
    func: faker.animal.cetacean,
    callSignature: "faker:animal:cetacean",
    tags: ["animal"],
  },
  {
    funcName: "Cow Name",
    funcDesc: "Generates a random cow name.",
    func: faker.animal.cow,
    callSignature: "faker:animal:cow",
    tags: ["animal"],
  },
  {
    funcName: "Crocodilia Name",
    funcDesc: "Generates a random crocodilia name.",
    func: faker.animal.crocodilia,
    callSignature: "faker:animal:crocodilia",
    tags: ["animal"],
  },
  {
    funcName: "Dog Name",
    funcDesc: "Generates a random dog name.",
    func: faker.animal.dog,
    callSignature: "faker:animal:dog",
    tags: ["animal"],
  },
  {
    funcName: "Fish Name",
    funcDesc: "Generates a random fish name.",
    func: faker.animal.fish,
    callSignature: "faker:animal:fish",
    tags: ["animal"],
  },
  {
    funcName: "Horse Name",
    funcDesc: "Generates a random horse name.",
    func: faker.animal.horse,
    callSignature: "faker:animal:horse",
    tags: ["animal"],
  },
  {
    funcName: "Insect Name",
    funcDesc: "Generates a random insect name.",
    func: faker.animal.insect,
    callSignature: "faker:animal:insect",
    tags: ["animal"],
  },
  {
    funcName: "Lion Name",
    funcDesc: "Generates a random lion name.",
    func: faker.animal.lion,
    callSignature: "faker:animal:lion",
    tags: ["animal"],
  },
  {
    funcName: "Rabbit Name",
    funcDesc: "Generates a random rabbit name.",
    func: faker.animal.rabbit,
    callSignature: "faker:animal:rabbit",
    tags: ["animal"],
  },
  {
    funcName: "Rodent Name",
    funcDesc: "Generates a random rodent name.",
    func: faker.animal.rodent,
    callSignature: "faker:animal:rodent",
    tags: ["animal"],
  },
  {
    funcName: "Snake Name",
    funcDesc: "Generates a random snake name.",
    func: faker.animal.snake,
    callSignature: "faker:animal:snake",
    tags: ["animal"],
  },
];
