import { faker } from "@faker-js/faker";

export const financeFn = [
  // Finance
  {
    funcName: "Account Number",
    funcDesc: "Generates a random account number.",
    func: faker.finance.accountNumber,
    callSignature: "faker:finance:accountNumber",
    tags: ["finance"],
  },
  {
    funcName: "Account Name",
    funcDesc: "Generates a random account name.",
    func: faker.finance.accountName,
    callSignature: "faker:finance:accountName",
    tags: ["finance"],
  },
  {
    funcName: "Amount",
    funcDesc: "Generates a random monetary amount.",
    func: faker.finance.amount,
    callSignature: "faker:finance:amount",
    tags: ["finance"],
  },
  {
    funcName: "Transaction Type",
    funcDesc: "Generates a random transaction type.",
    func: faker.finance.transactionType,
    callSignature: "faker:finance:transactionType",
    tags: ["finance"],
  },
  {
    funcName: "Currency Code",
    funcDesc: "Generates a random currency code.",
    func: faker.finance.currencyCode,
    callSignature: "faker:finance:currencyCode",
    tags: ["finance"],
  },
  {
    funcName: "Currency Name",
    funcDesc: "Generates a random currency name.",
    func: faker.finance.currencyName,
    callSignature: "faker:finance:currencyName",
    tags: ["finance"],
  },
  {
    funcName: "Currency Symbol",
    funcDesc: "Generates a random currency symbol.",
    func: faker.finance.currencySymbol,
    callSignature: "faker:finance:currencySymbol",
    tags: ["finance"],
  },
  {
    funcName: "Credit Card Number",
    funcDesc: "Generates a random credit card number.",
    func: faker.finance.creditCardNumber,
    callSignature: "faker:finance:creditCardNumber",
    tags: ["finance"],
  },
  {
    funcName: "Credit Card CVV",
    funcDesc: "Generates a random credit card CVV.",
    func: faker.finance.creditCardCVV,
    callSignature: "faker:finance:creditCardCVV",
    tags: ["finance"],
  },
  {
    funcName: "Bitcoin Address",
    funcDesc: "Generates a random Bitcoin address.",
    func: faker.finance.bitcoinAddress,
    callSignature: "faker:finance:bitcoinAddress",
    tags: ["finance"],
  },
  {
    funcName: "Ethereum Address",
    funcDesc: "Generates a random Ethereum address.",
    func: faker.finance.ethereumAddress,
    callSignature: "faker:finance:ethereumAddress",
    tags: ["finance"],
  },
  {
    funcName: "IBAN",
    funcDesc: "Generates a random International Bank Account Number (IBAN).",
    func: faker.finance.iban,
    callSignature: "faker:finance:iban",
    tags: ["finance"],
  },
  {
    funcName: "BIC",
    funcDesc: "Generates a random Bank Identifier Code (BIC).",
    func: faker.finance.bic,
    callSignature: "faker:finance:bic",
    tags: ["finance"],
  },
  {
    funcName: "Routing Number",
    funcDesc: "Generates a random bank routing number.",
    func: faker.finance.routingNumber,
    callSignature: "faker:finance:routingNumber",
    tags: ["finance"],
  },
  {
    funcName: "Transaction Description",
    funcDesc: "Generates a random transaction description.",
    func: faker.finance.transactionDescription,
    callSignature: "faker:finance:transactionDescription",
    tags: ["finance"],
  },
];
