import { faker } from "@faker-js/faker";

export const internetFn = [
  // Internet
  {
    funcName: "Display Name",
    funcDesc: "Generates a random display name.",
    func: faker.internet.displayName,
    callSignature: "faker:internet:displayName",
    tags: ["internet"],
  },
  {
    funcName: "Username",
    funcDesc: "Generates a random username.",
    func: faker.internet.username,
    callSignature: "faker:internet:userName",
    tags: ["internet"],
  },
  {
    funcName: "Email",
    funcDesc: "Generates a random email address.",
    func: faker.internet.email,
    callSignature: "faker:internet:email",
    tags: ["internet"],
  },
  {
    funcName: "Example Email",
    funcDesc: "Generates a random example email address.",
    func: faker.internet.exampleEmail,
    callSignature: "faker:internet:exampleEmail",
    tags: ["internet"],
  },
  {
    funcName: "Domain Name",
    funcDesc: "Generates a random domain name.",
    func: faker.internet.domainName,
    callSignature: "faker:internet:domainName",
    tags: ["internet"],
  },
  {
    funcName: "Domain Word",
    funcDesc: "Generates a random domain word.",
    func: faker.internet.domainWord,
    callSignature: "faker:internet:domainWord",
    tags: ["internet"],
  },
  {
    funcName: "Domain Suffix",
    funcDesc: "Generates a random domain suffix.",
    func: faker.internet.domainSuffix,
    callSignature: "faker:internet:domainSuffix",
    tags: ["internet"],
  },
  {
    funcName: "IP Address (IPv4)",
    funcDesc: "Generates a random IPv4 address.",
    func: faker.internet.ip,
    callSignature: "faker:internet:ip",
    tags: ["internet"],
  },
  {
    funcName: "IP Address (IPv6)",
    funcDesc: "Generates a random IPv6 address.",
    func: faker.internet.ipv6,
    callSignature: "faker:internet:ipv6",
    tags: ["internet"],
  },
  {
    funcName: "MAC Address",
    funcDesc: "Generates a random MAC address.",
    func: faker.internet.mac,
    callSignature: "faker:internet:mac",
    tags: ["internet"],
  },
  {
    funcName: "Password",
    funcDesc: "Generates a random password.",
    func: faker.internet.password,
    callSignature: "faker:internet:password",
    tags: ["internet"],
  },
  {
    funcName: "URL",
    funcDesc: "Generates a random URL.",
    func: faker.internet.url,
    callSignature: "faker:internet:url",
    tags: ["internet"],
  },
  {
    funcName: "HTTP Method",
    funcDesc: "Generates a random HTTP method.",
    func: faker.internet.httpMethod,
    callSignature: "faker:internet:httpMethod",
    tags: ["internet"],
  },
  {
    funcName: "User Agent",
    funcDesc: "Generates a random User Agent.",
    func: faker.internet.userAgent,
    callSignature: "faker:internet:userAgent",
    tags: ["internet"],
  },
  {
    funcName: "Emoji",
    funcDesc: "Generates a random emoji.",
    func: faker.internet.emoji,
    callSignature: "faker:internet:emoji",
    tags: ["internet"],
  },
];
