import { faker } from "@faker-js/faker";

export const locationFn = [
  // Location
  {
    funcName: "Latitude",
    funcDesc: "Generates a random latitude coordinate.",
    func: faker.location.latitude,
    callSignature: "faker:location:latitude",
    tags: ["location"],
  },
  {
    funcName: "Longitude",
    funcDesc: "Generates a random longitude coordinate.",
    func: faker.location.longitude,
    callSignature: "faker:location:longitude",
    tags: ["location"],
  },
  {
    funcName: "Country",
    funcDesc: "Generates a random country name.",
    func: faker.location.country,
    callSignature: "faker:location:country",
    tags: ["location"],
  },
  {
    funcName: "Continent",
    funcDesc: "Generates a random continent name.",
    func: faker.location.continent,
    callSignature: "faker:location:continent",
    tags: ["location"],
  },
  {
    funcName: "Country Code",
    funcDesc: "Generates a random country code.",
    func: faker.location.countryCode,
    callSignature: "faker:location:countryCode",
    tags: ["location"],
  },
  {
    funcName: "State",
    funcDesc: "Generates a random state or province name.",
    func: faker.location.state,
    callSignature: "faker:location:state",
    tags: ["location"],
  },
  {
    funcName: "County",
    funcDesc: "Generates a random county name.",
    func: faker.location.country,
    callSignature: "faker:location:country",
    tags: ["location"],
  },
  {
    funcName: "Cardinal Direction",
    funcDesc: "Generates a random cardinal direction.",
    func: faker.location.cardinalDirection,
    callSignature: "faker:location:cardinalDirection",
    tags: ["location"],
  },
  {
    funcName: "Direction",
    funcDesc: "Generates a random direction.",
    func: faker.location.direction,
    callSignature: "faker:location:direction",
    tags: ["location"],
  },
  {
    funcName: "City",
    funcDesc: "Generates a random city name.",
    func: faker.location.city,
    callSignature: "faker:location:city",
    tags: ["location"],
  },
  {
    funcName: "Street Name",
    funcDesc: "Generates a random street name.",
    func: faker.location.street,
    callSignature: "faker:location:street",
    tags: ["location"],
  },
  {
    funcName: "Street Address",
    funcDesc: "Generates a random street address.",
    func: faker.location.streetAddress,
    callSignature: "faker:location:streetAddress",
    tags: ["location"],
  },
  {
    funcName: "Zip Code",
    funcDesc: "Generates a random zip/postal code.",
    func: faker.location.zipCode,
    callSignature: "faker:location:zipCode",
    tags: ["location"],
  },
  {
    funcName: "Time Zone",
    funcDesc: "Generates a random time zone.",
    func: faker.location.timeZone,
    callSignature: "faker:location:timeZone",
    tags: ["location"],
  },
  {
    funcName: "GPS Coordinate",
    funcDesc: "Generates a random GPS coordinate.",
    func: faker.location.nearbyGPSCoordinate,
    callSignature: "faker:location:nearbyGPSCoordinate",
    tags: ["location"],
  },
];
