import { faker } from "@faker-js/faker";

export const personFn = [
  {
    funcName: "First Name",
    funcDesc: "Generates a random first name.",
    func: faker.person.firstName,
    callSignature: "faker:person:firstName",
    tags: ["person"],
  },
  {
    funcName: "Last Name",
    funcDesc: "Generates a random last name.",
    func: faker.person.lastName,
    callSignature: "faker:person:lastName",
    tags: ["person"],
  },
  {
    funcName: "Middle Name",
    funcDesc: "Generates a random middle name.",
    func: faker.person.middleName,
    callSignature: "faker:person:middleName",
    tags: ["person"],
  },
  {
    funcName: "Full Name",
    funcDesc: "Generates a random full name.",
    func: faker.person.fullName,
    callSignature: "faker:person:fullName",
    tags: ["person"],
  },
  {
    funcName: "Job Title",
    funcDesc: "Generates a random job title.",
    func: faker.person.jobTitle,
    callSignature: "faker:person:jobTitle",
    tags: ["person"],
  },
  {
    funcName: "Job Descriptor",
    funcDesc: "Generates a random job descriptor.",
    func: faker.person.jobDescriptor,
    callSignature: "faker:person:jobDescriptor",
    tags: ["person"],
  },
  {
    funcName: "Job Area",
    funcDesc: "Generates a random job area.",
    func: faker.person.jobArea,
    callSignature: "faker:person:jobArea",
    tags: ["person"],
  },
  {
    funcName: "Job Type",
    funcDesc: "Generates a random job type.",
    func: faker.person.jobType,
    callSignature: "faker:person:jobType",
    tags: ["person"],
  },
  {
    funcName: "Prefix",
    funcDesc: "Generates a random prefix (e.g., Mr., Ms.).",
    func: faker.person.prefix,
    callSignature: "faker:person:prefix",
    tags: ["person"],
  },
  {
    funcName: "Suffix",
    funcDesc: "Generates a random suffix (e.g., Jr., PhD).",
    func: faker.person.suffix,
    callSignature: "faker:person:suffix",
    tags: ["person"],
  },
  {
    funcName: "Biography",
    funcDesc: "Generates a random short biography.",
    func: faker.person.bio,
    callSignature: "faker:person:bio",
    tags: ["person"],
  },
  {
    funcName: "Gender",
    funcDesc: "Generates a random gender.",
    func: faker.person.gender,
    callSignature: "faker:person:gender",
    tags: ["person"],
  },
  {
    funcName: "Zodiac Sign",
    funcDesc: "Generates a random zodiac sign.",
    func: faker.person.zodiacSign,
    callSignature: "faker:person:zodiacSign",
    tags: ["person"],
  },
];
